### PR TITLE
Allow up to 275 adapters for qemu

### PR DESCRIPTION
**Pull request by noplay**
See #889 for more details

### CODE REVIEW

**Comment by grossmj** [comment]
I've tried to configure a Qemu VM with 64 adapters but looks like my Qemu doesn't support it:

```
qemu-system-i386 --version
QEMU emulator version 2.0.0 (Debian 2.0.0+dfsg-2ubuntu1.31), Copyright (c) 2003-2008 Fabrice Bellard
```

```
=> QEMU process has stopped, return code: 1
Start QEMU with /usr/bin/qemu-system-i386 -name MicroCoreLinux6.4-1 -m 64M -smp cpus=1 -enable-kvm -boot order=c -drive file=/home/grossmj/GNS3/projects/QEMU_275/project-files/qemu/be112ade-d9ef-4ecf-9a7b-bfcba1d4f891/hda_disk.qcow2,if=ide,index=0,media=disk -uuid be112ade-d9ef-4ecf-9a7b-bfcba1d4f891 -serial telnet:127.0.0.1:5003,server,nowait -monitor tcp:127.0.0.1:52165,server,nowait -net none -device i82801b11-bridge,id=dmi_pci_bridge1 -device pci-bridge,id=pci-bridge1,bus=dmi_pci_bridge1,chassis_nr=0x1,addr=0x1,shpc=off -device i82801b11-bridge,id=dmi_pci_bridge2 -device pci-bridge,id=pci-bridge2,bus=dmi_pci_bridge2,chassis_nr=0x1,addr=0x2,shpc=off -device e1000,mac=00:aa:52:f8:91:00,netdev=gns3-0 -netdev socket,id=gns3-0,udp=127.0.0.1:10001,localaddr=0.0.0.0:10000 -device e1000,mac=00:aa:52:f8:91:01,netdev=gns3-1 -netdev socket,id=gns3-1,udp=127.0.0.1:10003,localaddr=0.0.0.0:10002 -device e1000,mac=00:aa:52:f8:91:02,netdev=gns3-2 -netdev socket,id=gns3-2,udp=127.0.0.1:10005,localaddr=0.0.0.0:10004 -device e1000,mac=00:aa:52:f8:91:03,netdev=gns3-3 -netdev socket,id=gns3-3,udp=127.0.0.1:10007,localaddr=0.0.0.0:10006 -device e1000,mac=00:aa:52:f8:91:04,netdev=gns3-4 -netdev socket,id=gns3-4,udp=127.0.0.1:10009,localaddr=0.0.0.0:10008 -device e1000,mac=00:aa:52:f8:91:05,netdev=gns3-5 -netdev socket,id=gns3-5,udp=127.0.0.1:10011,localaddr=0.0.0.0:10010 -device e1000,mac=00:aa:52:f8:91:06,netdev=gns3-6 -netdev socket,id=gns3-6,udp=127.0.0.1:10013,localaddr=0.0.0.0:10012 -device e1000,mac=00:aa:52:f8:91:07,netdev=gns3-7 -netdev socket,id=gns3-7,udp=127.0.0.1:10015,localaddr=0.0.0.0:10014 -device e1000,mac=00:aa:52:f8:91:08,netdev=gns3-8 -netdev socket,id=gns3-8,udp=127.0.0.1:10017,localaddr=0.0.0.0:10016 -device e1000,mac=00:aa:52:f8:91:09,netdev=gns3-9 -netdev socket,id=gns3-9,udp=127.0.0.1:10019,localaddr=0.0.0.0:10018 -device e1000,mac=00:aa:52:f8:91:0a,netdev=gns3-10 -netdev socket,id=gns3-10,udp=127.0.0.1:10021,localaddr=0.0.0.0:10020 -device e1000,mac=00:aa:52:f8:91:0b,netdev=gns3-11 -netdev socket,id=gns3-11,udp=127.0.0.1:10023,localaddr=0.0.0.0:10022 -device e1000,mac=00:aa:52:f8:91:0c,netdev=gns3-12 -netdev socket,id=gns3-12,udp=127.0.0.1:10025,localaddr=0.0.0.0:10024 -device e1000,mac=00:aa:52:f8:91:0d,netdev=gns3-13 -netdev socket,id=gns3-13,udp=127.0.0.1:10027,localaddr=0.0.0.0:10026 -device e1000,mac=00:aa:52:f8:91:0e,netdev=gns3-14 -netdev socket,id=gns3-14,udp=127.0.0.1:10029,localaddr=0.0.0.0:10028 -device e1000,mac=00:aa:52:f8:91:0f,netdev=gns3-15 -netdev socket,id=gns3-15,udp=127.0.0.1:10031,localaddr=0.0.0.0:10030 -device e1000,mac=00:aa:52:f8:91:10,netdev=gns3-16 -netdev socket,id=gns3-16,udp=127.0.0.1:10033,localaddr=0.0.0.0:10032 -device e1000,mac=00:aa:52:f8:91:11,netdev=gns3-17 -netdev socket,id=gns3-17,udp=127.0.0.1:10035,localaddr=0.0.0.0:10034 -device e1000,mac=00:aa:52:f8:91:12,netdev=gns3-18 -netdev socket,id=gns3-18,udp=127.0.0.1:10037,localaddr=0.0.0.0:10036 -device e1000,mac=00:aa:52:f8:91:13,netdev=gns3-19 -netdev socket,id=gns3-19,udp=127.0.0.1:10039,localaddr=0.0.0.0:10038 -device e1000,mac=00:aa:52:f8:91:14,netdev=gns3-20 -netdev socket,id=gns3-20,udp=127.0.0.1:10041,localaddr=0.0.0.0:10040 -device e1000,mac=00:aa:52:f8:91:15,netdev=gns3-21 -netdev socket,id=gns3-21,udp=127.0.0.1:10043,localaddr=0.0.0.0:10042 -device e1000,mac=00:aa:52:f8:91:16,netdev=gns3-22 -netdev socket,id=gns3-22,udp=127.0.0.1:10045,localaddr=0.0.0.0:10044 -device e1000,mac=00:aa:52:f8:91:17,netdev=gns3-23 -netdev socket,id=gns3-23,udp=127.0.0.1:10047,localaddr=0.0.0.0:10046 -device e1000,mac=00:aa:52:f8:91:18,netdev=gns3-24 -netdev socket,id=gns3-24,udp=127.0.0.1:10049,localaddr=0.0.0.0:10048 -device e1000,mac=00:aa:52:f8:91:19,netdev=gns3-25 -netdev socket,id=gns3-25,udp=127.0.0.1:10051,localaddr=0.0.0.0:10050 -device e1000,mac=00:aa:52:f8:91:1a,bus=pci-bridge1,addr=0x00,netdev=gns3-26 -netdev socket,id=gns3-26,udp=127.0.0.1:10053,localaddr=0.0.0.0:10052 -device e1000,mac=00:aa:52:f8:91:1b,bus=pci-bridge1,addr=0x01,netdev=gns3-27 -netdev socket,id=gns3-27,udp=127.0.0.1:10055,localaddr=0.0.0.0:10054 -device e1000,mac=00:aa:52:f8:91:1c,bus=pci-bridge1,addr=0x02,netdev=gns3-28 -netdev socket,id=gns3-28,udp=127.0.0.1:10057,localaddr=0.0.0.0:10056 -device e1000,mac=00:aa:52:f8:91:1d,bus=pci-bridge1,addr=0x03,netdev=gns3-29 -netdev socket,id=gns3-29,udp=127.0.0.1:10059,localaddr=0.0.0.0:10058 -device e1000,mac=00:aa:52:f8:91:1e,bus=pci-bridge1,addr=0x04,netdev=gns3-30 -netdev socket,id=gns3-30,udp=127.0.0.1:10061,localaddr=0.0.0.0:10060 -device e1000,mac=00:aa:52:f8:91:1f,bus=pci-bridge1,addr=0x05,netdev=gns3-31 -netdev socket,id=gns3-31,udp=127.0.0.1:10063,localaddr=0.0.0.0:10062 -device e1000,mac=00:aa:52:f8:91:20,bus=pci-bridge1,addr=0x06,netdev=gns3-32 -netdev socket,id=gns3-32,udp=127.0.0.1:10065,localaddr=0.0.0.0:10064 -device e1000,mac=00:aa:52:f8:91:21,bus=pci-bridge1,addr=0x07,netdev=gns3-33 -netdev socket,id=gns3-33,udp=127.0.0.1:10067,localaddr=0.0.0.0:10066 -device e1000,mac=00:aa:52:f8:91:22,bus=pci-bridge1,addr=0x08,netdev=gns3-34 -netdev socket,id=gns3-34,udp=127.0.0.1:10069,localaddr=0.0.0.0:10068 -device e1000,mac=00:aa:52:f8:91:23,bus=pci-bridge1,addr=0x09,netdev=gns3-35 -netdev socket,id=gns3-35,udp=127.0.0.1:10071,localaddr=0.0.0.0:10070 -device e1000,mac=00:aa:52:f8:91:24,bus=pci-bridge1,addr=0x0a,netdev=gns3-36 -netdev socket,id=gns3-36,udp=127.0.0.1:10073,localaddr=0.0.0.0:10072 -device e1000,mac=00:aa:52:f8:91:25,bus=pci-bridge1,addr=0x0b,netdev=gns3-37 -netdev socket,id=gns3-37,udp=127.0.0.1:10075,localaddr=0.0.0.0:10074 -device e1000,mac=00:aa:52:f8:91:26,bus=pci-bridge1,addr=0x0c,netdev=gns3-38 -netdev socket,id=gns3-38,udp=127.0.0.1:10077,localaddr=0.0.0.0:10076 -device e1000,mac=00:aa:52:f8:91:27,bus=pci-bridge1,addr=0x0d,netdev=gns3-39 -netdev socket,id=gns3-39,udp=127.0.0.1:10079,localaddr=0.0.0.0:10078 -device e1000,mac=00:aa:52:f8:91:28,bus=pci-bridge1,addr=0x0e,netdev=gns3-40 -netdev socket,id=gns3-40,udp=127.0.0.1:10081,localaddr=0.0.0.0:10080 -device e1000,mac=00:aa:52:f8:91:29,bus=pci-bridge1,addr=0x0f,netdev=gns3-41 -netdev socket,id=gns3-41,udp=127.0.0.1:10083,localaddr=0.0.0.0:10082 -device e1000,mac=00:aa:52:f8:91:2a,bus=pci-bridge1,addr=0x10,netdev=gns3-42 -netdev socket,id=gns3-42,udp=127.0.0.1:10085,localaddr=0.0.0.0:10084 -device e1000,mac=00:aa:52:f8:91:2b,bus=pci-bridge1,addr=0x11,netdev=gns3-43 -netdev socket,id=gns3-43,udp=127.0.0.1:10087,localaddr=0.0.0.0:10086 -device e1000,mac=00:aa:52:f8:91:2c,bus=pci-bridge1,addr=0x12,netdev=gns3-44 -netdev socket,id=gns3-44,udp=127.0.0.1:10089,localaddr=0.0.0.0:10088 -device e1000,mac=00:aa:52:f8:91:2d,bus=pci-bridge1,addr=0x13,netdev=gns3-45 -netdev socket,id=gns3-45,udp=127.0.0.1:10091,localaddr=0.0.0.0:10090 -device e1000,mac=00:aa:52:f8:91:2e,bus=pci-bridge1,addr=0x14,netdev=gns3-46 -netdev socket,id=gns3-46,udp=127.0.0.1:10093,localaddr=0.0.0.0:10092 -device e1000,mac=00:aa:52:f8:91:2f,bus=pci-bridge1,addr=0x15,netdev=gns3-47 -netdev socket,id=gns3-47,udp=127.0.0.1:10095,localaddr=0.0.0.0:10094 -device e1000,mac=00:aa:52:f8:91:30,bus=pci-bridge1,addr=0x16,netdev=gns3-48 -netdev socket,id=gns3-48,udp=127.0.0.1:10097,localaddr=0.0.0.0:10096 -device e1000,mac=00:aa:52:f8:91:31,bus=pci-bridge1,addr=0x17,netdev=gns3-49 -netdev socket,id=gns3-49,udp=127.0.0.1:10099,localaddr=0.0.0.0:10098 -device e1000,mac=00:aa:52:f8:91:32,bus=pci-bridge1,addr=0x18,netdev=gns3-50 -netdev socket,id=gns3-50,udp=127.0.0.1:10101,localaddr=0.0.0.0:10100 -device e1000,mac=00:aa:52:f8:91:33,bus=pci-bridge1,addr=0x19,netdev=gns3-51 -netdev socket,id=gns3-51,udp=127.0.0.1:10103,localaddr=0.0.0.0:10102 -device e1000,mac=00:aa:52:f8:91:34,bus=pci-bridge1,addr=0x1a,netdev=gns3-52 -netdev socket,id=gns3-52,udp=127.0.0.1:10105,localaddr=0.0.0.0:10104 -device e1000,mac=00:aa:52:f8:91:35,bus=pci-bridge1,addr=0x1b,netdev=gns3-53 -netdev socket,id=gns3-53,udp=127.0.0.1:10107,localaddr=0.0.0.0:10106 -device e1000,mac=00:aa:52:f8:91:36,bus=pci-bridge1,addr=0x1c,netdev=gns3-54 -netdev socket,id=gns3-54,udp=127.0.0.1:10109,localaddr=0.0.0.0:10108 -device e1000,mac=00:aa:52:f8:91:37,bus=pci-bridge1,addr=0x1d,netdev=gns3-55 -netdev socket,id=gns3-55,udp=127.0.0.1:10111,localaddr=0.0.0.0:10110 -device e1000,mac=00:aa:52:f8:91:38,bus=pci-bridge1,addr=0x1e,netdev=gns3-56 -netdev socket,id=gns3-56,udp=127.0.0.1:10113,localaddr=0.0.0.0:10112 -device e1000,mac=00:aa:52:f8:91:39,bus=pci-bridge1,addr=0x1f,netdev=gns3-57 -netdev socket,id=gns3-57,udp=127.0.0.1:10115,localaddr=0.0.0.0:10114 -device e1000,mac=00:aa:52:f8:91:3a,bus=pci-bridge2,addr=0x00,netdev=gns3-58 -netdev socket,id=gns3-58,udp=127.0.0.1:10117,localaddr=0.0.0.0:10116 -device e1000,mac=00:aa:52:f8:91:3b,bus=pci-bridge2,addr=0x01,netdev=gns3-59 -netdev socket,id=gns3-59,udp=127.0.0.1:10119,localaddr=0.0.0.0:10118 -device e1000,mac=00:aa:52:f8:91:3c,bus=pci-bridge2,addr=0x02,netdev=gns3-60 -netdev socket,id=gns3-60,udp=127.0.0.1:10121,localaddr=0.0.0.0:10120 -device e1000,mac=00:aa:52:f8:91:3d,bus=pci-bridge2,addr=0x03,netdev=gns3-61 -netdev socket,id=gns3-61,udp=127.0.0.1:10123,localaddr=0.0.0.0:10122 -device e1000,mac=00:aa:52:f8:91:3e,bus=pci-bridge2,addr=0x04,netdev=gns3-62 -netdev socket,id=gns3-62,udp=127.0.0.1:10125,localaddr=0.0.0.0:10124 -device e1000,mac=00:aa:52:f8:91:3f,bus=pci-bridge2,addr=0x05,netdev=gns3-63 -netdev socket,id=gns3-63,udp=127.0.0.1:10127,localaddr=0.0.0.0:10126 -nographic

Execution log:
qemu-system-i386: -device pci-bridge,id=pci-bridge1,bus=dmi_pci_bridge1,chassis_nr=0x1,addr=0x1,shpc=off: Property '.shpc' not found
```

**Comment by noplay** [comment]
I can't found in qemu changelog where this propery has changed :(

**Comment by noplay** [comment]
I guess it started with 2.4:
https://lists.nongnu.org/archive/html/qemu-devel/2015-06/msg05142.html
http://wiki.qemu-project.org/ChangeLog/2.4#PCI.2FPCIe

I will make a patch that raise an error you qemu 2.4 and later for more devices.

**Comment by noplay** [comment]
Now it's raise an error if you use qemu < 2.4 with a large number of adapter

**Pull request merged**
