### PR TITLE
Minor cleanup on docker-init

### PR DESCRIPTION
**Pull request by ehlers**
Some minor cleanup
- avoid warnings by adding /etc/network/pre-up.d and post-down.d
- shell wrappers for udhcpc and udhcpc6 no longer necessary, script path has been changed in busybox

### CODE REVIEW

**Comment by ehlers** [comment]
The tests on 1.5 are failing since this commit:
1.5 New console port range 5000 to 10000.

**Comment by ehlers** [comment]
Just one more idea:

Currently the busybox ifupdown gives up getting a lease after 5 tries. It's the option `-n` of udhcpc, which is responsible for that. When using `-b` instead, it should continue to try to get a lease in the background (according to the documentation, I haven't tried).

To change that in the config file of the busybox build
`CONFIG_IFUPDOWN_UDHCPC_CMD_OPTIONS="-R -n"`
should be replaced by
`CONFIG_IFUPDOWN_UDHCPC_CMD_OPTIONS="-R -b"`

**Comment by noplay** [comment]
I pushed a fix on 1.5 for the test failed

**Comment by noplay** [comment]
Thanks !

**Pull request merged**
