### PR TITLE
Update export_project.py. Limit reinitializing MAC addresses to cloud nodes.

### PR DESCRIPTION
**Pull request by fadlytabrani**
Limit reinitializing MAC addresses to cloud nodes. Resolves issue #1762 .

### CODE REVIEW

**Comment by grossmj** [comment]
@fadlytabrani thanks for the PR however this won't work because "Cloud" nodes are more like a pseudo node to show an external connection in GNS3. A cloud node itself has no MAC address property.

Something like this would work:

1. For all nodes with the "mac_addr" or "mac_address" property.
2. Find all the interfaces is connected to a cloud.
3. Change/reset the mac address for this interface.

However, the MAC address property is at the node level, so you would have to reset the MAC address for all the interfaces. We do support custom interfaces for some node types but I believe we shouldn't add or change custom interfaces when an user export or import a project.

I will comment on https://github.com/GNS3/gns3-server/issues/1762 to provide an alternative.

**Comment by fadlytabrani** [comment]
Agreed. I have just realized that after looking at the cloud node properties. Generally I disable cloud nodes and utilise nat instead. Can you consider the following options?


1. Is there anyway we can do a discovery via topology links and only reinitialize mac addresses for nodes/ports that are attached to cloud nodes?

2. Since resetting mac addresses is an option in the function, can we expose it as part of an option (checkbox) when doing exports in the GUI?

**Comment by grossmj** [comment]
> Is there anyway we can do a discovery via topology links and only reinitialize mac addresses for nodes/ports that are attached to cloud nodes?

We could do something like that but this would add too much complexity.

> Since resetting mac addresses is an option in the function, can we expose it as part of an option (checkbox) when doing exports in the GUI?

This would be a better approach as explained in https://github.com/GNS3/gns3-server/issues/1762

I can take care of this, I just need to expose the option in either the export or import function.

**Comment by grossmj** [comment]
This has been taken care in https://github.com/GNS3/gns3-server/pull/1764

**Pull request closed without merging**
