### PR TITLE
Aiohttp 2.0

### PR DESCRIPTION
**Pull request by noplay**
Ref #1000

### CODE REVIEW

**Comment by grossmj** [comment]
There are issues loading labs.

svg_issue

```
QSvgHandler: Width or height for "data:image/png;base64," image was not greater than 0
Cannot read file '/tmp/tmpxymtx2rq/b4625a5a801e68d455bd5cf0012a088f.svg', because: Premature end of document. (line 1)
QSvgHandler: Width or height for "data:image/png;base64," image was not greater than 0
```

**Comment by noplay** [comment]
It's standard router image?

**Comment by grossmj** [comment]
Yes

**Comment by noplay** [comment]
It's with last 2.1 code for GUI? I didn't reproduce it :(

**Comment by noplay** [comment]
But it's possible we introduce a bug with old Qt because the way to send file has changed now it's chunked I will try to make it with a content length ...

**Comment by noplay** [comment]
Could you test again?

**Comment by grossmj** [comment]
Seems that the symbol don't vanish anymore however I get "project not opened" messages all the time when moving a node on the scene...

project_not_opened

**Comment by noplay** [comment]
**** buggy old Qt

**Comment by noplay** [comment]
Which version of Qt are you using? 

I don't see anything wrong on HTTP level :( The response are the same and it doesn't fail on my computer.

**Comment by grossmj** [comment]
I tested with latest versions: Python 3.5.2 Qt 5.8.0 and PyQt 5.8.2.

**Comment by grossmj** [comment]
Same issue with Python 3.5.2 Qt 5.5.1 and PyQt 5.5.1.

**Comment by grossmj** [comment]
Creating a lab from scratch, same problem :(

**Comment by grossmj** [comment]
This was due to an old aiohttp version... :/

**Pull request merged**
