### PR TITLE
Create endpoint in symbols handler to get symbol dimensions #1884

### PR DESCRIPTION
**Pull request by piotrpekala7**
We need to create endpoint to get server dimensions for https://github.com/GNS3/gns3-web-ui/issues/1047

### CODE REVIEW

**Comment by piotrpekala7** [comment]
@grossmj 
when I tried to use get_size from symbol class
```
    @Route.get(
        r"/symbols/{symbol_id:.+}/dimensions",
        description="Get the symbol dimensions",
        status_codes={
            200: "Symbol dimensions returned"
        })
    async def raw(request, response):

        controller = Controller.instance()
        symbol_id = urllib.parse.unquote(request.match_info["symbol_id"])
        try:
            width, height, _ = controller.symbols.get_size(symbol_id)
            symbol_dimensions = { 'width': width, 'height': height }
            response.json(symbol_dimensions)
        except (KeyError, OSError) as e:
            log.warning("Could not get symbol file: {}".format(e))
            response.set_status(404)
```
 it returns 0, 0 when svg starts with 
`<svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" height=\"300\" \n                width=\"300\">`

**Comment by piotrpekala7** [comment]
> @grossmj
> when I tried to use get_size from symbol class
> 
> ```
>     @Route.get(
>         r"/symbols/{symbol_id:.+}/dimensions",
>         description="Get the symbol dimensions",
>         status_codes={
>             200: "Symbol dimensions returned"
>         })
>     async def raw(request, response):
> 
>         controller = Controller.instance()
>         symbol_id = urllib.parse.unquote(request.match_info["symbol_id"])
>         try:
>             width, height, _ = controller.symbols.get_size(symbol_id)
>             symbol_dimensions = { 'width': width, 'height': height }
>             response.json(symbol_dimensions)
>         except (KeyError, OSError) as e:
>             log.warning("Could not get symbol file: {}".format(e))
>             response.set_status(404)
> ```
> 
> it returns 0, 0 when svg starts with
> `<svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" height=\"300\" \n width=\"300\">`

it looks like one condition was missing https://github.com/GNS3/gns3-server/pull/1885/files#diff-82ab42d622e48c761119db7718302aa5c508f16d3d5cde78d19af024180a2dccR95

**Comment by piotrpekala7** [comment]
@grossmj thanks!

**Comment by b-ehlers** [comment]
Two suggestions for improvements:

- get_size from gns3server.utils.picture is not used, import can be removed. The get_size used is a method of the Symbols class.
- get_size may throw the ValueError exception, it might be better to catch it.

Patch:

```
diff --git a/gns3server/handlers/api/controller/symbol_handler.py b/gns3server/handlers/api/controller/symbol_handler.py
index cb7139f7..30da3755 100644
--- a/gns3server/handlers/api/controller/symbol_handler.py
+++ b/gns3server/handlers/api/controller/symbol_handler.py
@@ -22,7 +22,6 @@ import urllib.parse
 
 from gns3server.web.route import Route
 from gns3server.controller import Controller
-from gns3server.utils.picture import get_size
 
 import logging
 log = logging.getLogger(__name__)
@@ -58,7 +57,7 @@ class SymbolHandler:
             width, height, _ = controller.symbols.get_size(symbol_id)
             symbol_dimensions = { 'width': width, 'height': height }
             response.json(symbol_dimensions)
-        except (KeyError, OSError) as e:
+        except (KeyError, OSError, ValueError) as e:
             log.warning("Could not get symbol file: {}".format(e))
             response.set_status(404)
 
```

**Pull request merged**
