### PR TITLE
gns3.service.openrc: make openrc script posix compliant

### PR DESCRIPTION
**Pull request by mm1ke**
Hi,

This is a small change to the open script to make it POSIX compliant.
I've also removed a trailing whitespace from the script.

Regards
Michael

### CODE REVIEW

**Comment by grossmj** [comment]
Thanks 👍

**Comment by mm1ke** [comment]
Hi,

I've just noticed that the latest version (2.2.34) doesn't include this fix.
Is this intended or somehow forgotten?

Regards
Michael

**Comment by grossmj** [comment]
We may have forgotten to merge master into the 2.2 branch. I will check...

**Comment by grossmj** [comment]
I was right, we forgot to merge before the last release. Sorry about this, it is done now: https://github.com/GNS3/gns3-server/commit/dced70a565e8f885f4442d6acbca19cf22590d86

**Pull request merged**
