### PR TITLE
Export files from remote server, Fixes: gui/#2271

### PR DESCRIPTION
**Pull request by ziajka**

### CODE REVIEW

**Comment by ziajka** [comment]
Don't merge it for now.

**Comment by ziajka** [comment]
Now is OK. Needed to check one thing.

**Comment by grossmj** [comment]
Everything seems to work well :+1:

**Comment by ziajka** [comment]
It's also necessary to check import as it also may have an impact.

**Comment by grossmj** [comment]
All good too.

**Pull request merged**
