### PR TITLE
Filters support for VMware

### LINKED ISSUE #1108: Filters support for VMware

### PR DESCRIPTION
**Pull request by noplay**
Fix #1108

### CODE REVIEW

**Comment by grossmj** [comment]
I cannot ping between 2 VMware VMs as soon as a filter is applied.

**Comment by grossmj** [comment]
Connecting to uBridge and adding a filter manually works.

**Comment by grossmj** [comment]
I suspect some other problem at play, I can see the filter is applied if I connect manually to uBridge.

```
bridge show ethernet0.vnet
101 bridge 'ethernet0.vnet' is running
101 Filter 'filter0' configured in position 1
101 Source NIO: vmnet3
101 Destination NIO: 10000:127.0.0.1:10001
100-OK
```

However, something happens in the VM and a new IP address is set on the network adapter.

filter_applied

**Comment by noplay** [comment]
Perhaps VMware decide to reconfigure the adapter for whatever reason

**Comment by grossmj** [comment]
Yes because I cannot reproduce it if I apply a filter manually. Maybe the VMX file gets rewritten which trigger something in the VM? I am still investigating...

**Comment by grossmj** [comment]
I am going to merge this since the problem doesn't seem to be related on the packet filter support itself.

**Pull request merged**
