### PR TITLE
duplicate fast

### PR DESCRIPTION
**Pull request by z5241248**
Project replication takes too long~

So, the code can improve the project copy function, directly copy the directory, so that it can copy several times faster.

### CODE REVIEW

**Comment by grossmj** [comment]
Thank you. I will review soon.

**Comment by grossmj** [comment]
@z5241248 hi, any reason you decide to close your PR?

**Comment by z5241248** [comment]
I optimized the code and resubmitted it.

[https://github.com/GNS3/gns3-server/pull/2413](https://github.com/GNS3/gns3-server/pull/2413)

**Comment by z5241248** [comment]
> @z5241248 hi, any reason you decide to close your PR?

I optimized the code and resubmitted it.

[https://github.com/GNS3/gns3-server/pull/2413](https://github.com/GNS3/gns3-server/pull/2413)

**Comment by grossmj** [comment]
Oh ok, I missed that. Thanks 👍

**Comment by z5241248** [comment]
> Oh ok, I missed that. Thanks 👍

Ok...…and...…how about the new PR? Could you please check and merge it?

**Pull request closed without merging**
