### PR TITLE
Change directory layout for dynamips.

### PR DESCRIPTION
**Pull request by noplay**
This create a directory by node to allow feature like save as
to work when running on multiple compute. Benefits now dynamips work
like other nodes. Old topologies are migrated at startup.

Ref https://github.com/GNS3/gns3-gui/issues/1761

### CODE REVIEW

**Comment by ehlers** [comment]
Conversion from old directory layout to the new one missing for devices running on remote servers.

**Comment by noplay** [comment]
Ok should work on remote now

**Comment by ehlers** [comment]
Tested with remote dynamips devices, works fine.

**Comment by noplay** [comment]
Thanks ! As usual your help is priceless.

**Pull request merged**
