### PR TITLE
Remote install on 14.04 ubuntu

### PR DESCRIPTION
**Pull request by noplay**
Setup GNS3 and a VPN on a naked ubuntu server 14.04. For people who want to install it on public hosting provider.

To test it as root:
```
cd /tmp
curl https://raw.githubusercontent.com/GNS3/gns3-server/remote_install/scripts/remote-install.sh > gns3-remote-install.sh
bash gns3-remote-install.sh --with-openvpn
```

At the end you got an url to an openvpn config file.

On mac you can use it with tunnel blick.

After that you can add a server 172.16.253.1 as a GNS3 remote server

### CODE REVIEW

**Comment by AJNOURI** [comment]
Great script, tested on amazon AWS ubuntu 14.04 image and for IOU to work:
```
sudo dpkg --add-architecture i386
sudo apt-get install gns3-iou

```
are required.

**Comment by noplay** [comment]
Yeah the issue with IOU at this time is I tested it on a cloud providers where only the 64 bits package are available :(

**Comment by noplay** [comment]
@AJNOURI did you test the VPN?

**Comment by AJNOURI** [comment]
Yes, it looks good:

> $ /usr/sbin/openvpn --config gns3-iouvm.ovpn
> Wed Mar 23 00:00:04 2016 OpenVPN 2.3.4 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [MH] [IPv6] built on Nov 12 2015
> Wed Mar 23 00:00:04 2016 library versions: OpenSSL 1.0.1k 8 Jan 2015, LZO 2.08
> Wed Mar 23 00:00:04 2016 WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.
> Wed Mar 23 00:00:04 2016 UDPv4 link local: [undef]
> Wed Mar 23 00:00:04 2016 UDPv4 link remote: [AF_INET]52.91.111.162:1194
> Wed Mar 23 00:00:05 2016 [OpenVPN] Peer Connection Initiated with [AF_INET]52.91.111.162:1194
> Wed Mar 23 00:00:08 2016 TUN/TAP device tun0 opened
> Wed Mar 23 00:00:08 2016 do_ifconfig, tt->ipv6=0, tt->did_ifconfig_ipv6_setup=0
> Wed Mar 23 00:00:08 2016 /sbin/ip link set dev tun0 up mtu 1500
> Wed Mar 23 00:00:08 2016 /sbin/ip addr add dev tun0 local 172.16.253.10 peer 172.16.253.9
> Wed Mar 23 00:00:08 2016 Initialization Sequence Completed
> 

From the server:

> $ sudo tcpdump -i tun1194
> tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
> listening on tun1194, link-type RAW (Raw IP), capture size 65535 bytes
> 23:05:02.831409 IP 172.16.253.10.33367 > 172.16.253.1.8000: Flags [S], seq 2718583169, win 29200, options [mss 1368,sackOK,TS val 68784502 ecr 0,nop,wscale 7], length 0
> 23:05:02.831449 IP 172.16.253.1.8000 > 172.16.253.10.33367: Flags [S.], seq 3452166939, ack 2718583170, win 28960, options [mss 1460,sackOK,TS val 40675 ecr 68784502,nop,wscale 7], length 0
> 23:05:02.944075 IP 172.16.253.10.33367 > 172.16.253.1.8000: Flags [.], ack 1, win 229, options [nop,nop,TS val 68784530 ecr 40675], length 0
> 23:05:02.947218 IP 172.16.253.10.33367 > 172.16.253.1.8000: Flags [P.], seq 1:222, ack 1, win 229, options [nop,nop,TS val 68784530 ecr 40675], length 221
> 23:05:02.947236 IP 172.16.253.1.8000 > 172.16.253.10.33367: Flags [.], ack 222, win 235, options [nop,nop,TS val 40704 ecr 68784530], length 0
> 23:05:03.060354 IP 172.16.253.10.33367 > 172.16.253.1.8000: Flags [P.], seq 222:224, ack 1, win 229, options [nop,nop,TS val 68784559 ecr 40704], length 2
> …
> 

image

**Comment by AJNOURI** [comment]
1) Tried installing an IOSv appliance (Rackspace), but I got:

image

According to rackspace, nested virtualization is not supported on virtual instances, only for dedicated servers. I am pretty sure it is the case with Amazon Aws.
Which exclude the numerous appliances GNS3 supports : ( What about dynamips?

2) Can't get IOU images, stable and working locally, to run remotely on Rackspace (only i86bi_linux_l2-ipbasek9-ms-may8-2013-team_track.bin works on Amazon)

Got this:

> 2016-03-26 23:21:31 INFO device.py:63 SW1 has been created
> 2016-03-26 23:21:31 INFO link.py:57 adding link from IOU2 Ethernet0/0 to SW1 1
> 2016-03-26 23:21:31 INFO link.py:57 adding link from IOU3 Ethernet0/0 to SW1 2
> 2016-03-26 23:21:32 INFO topology.py:946 Topology initialized
> 2016-03-26 23:21:44 INFO vm.py:146 IOU3 has started
> 2016-03-26 23:21:44 INFO vm.py:146 IOU2 has started
> 2016-03-26 23:21:49 ERROR project.py:385 IOU process has stopped, return code: -11
> 
> Error: IOU process has stopped, return code: -11
> 
> 2016-03-26 23:21:49 ERROR project.py:385 IOU process has stopped, return code: -11
> 
> Error: IOU process has stopped, return code: -11
>

**Comment by noplay** [comment]
Yes virtualization instructions is rare. AWS doesn't provide it.

At this time only bare metal provider could support KVM. In theory an Hyper-V or VMware provider could offer it.

Can you try to start an IOU process by hand?

**Comment by grossmj** [comment]
Hi,

-11 means a SEGFAULT. Your IOU has crashed, you may find a log file in the project directory that will give a little more information but I don't think we will be able to do something about it.

Regarding KVM support you may want to have a look at packet.net

**Comment by AJNOURI** [comment]
@noplay, How to start an IOU process by hand?
@grossmj, Thanks for the resource. Cool stuff and much cheaper relatively to amazon and rackspace.

**Comment by noplay** [comment]
AJ for french people https://www.scaleway.com/ should be able to do the
job. But for the moment KVM is not enable (The CPU should support it).

For starting an IOU (IOU is a standard linux program):
 ./i86bi-linux-l3-adventerprisek9-15.4.1T.bin 1

Does it SIGSEV?

**Comment by AJNOURI** [comment]
Thanks for the link Julien.
Indeed, returned SIGSEV:
> ./i86bi-linux-l3-adventerprisek9-ms.155-2.T.bin 1
> Segmentation fault
>

**Comment by noplay** [comment]
What is the content of your /etc/apt/source.list?

**Comment by noplay** [comment]
I wonder if your repositories send your the last version of libssl.

**Comment by grossmj** [comment]
Make sure the IOU image is not corrupted.

**Comment by AJNOURI** [comment]
@noplay 
cat  /etc/apt/sources.list
```
# deb http://mirror.rackspace.com/ubuntu trusty main restricted

# deb http://mirror.rackspace.com/ubuntu trusty-updates main restricted
# deb http://mirror.rackspace.com/ubuntu trusty-security main restricted

# See http://help.ubuntu.com/community/UpgradeNotes for how to upgrade to
# newer versions of the distribution.
deb http://mirror.rackspace.com/ubuntu trusty main restricted
deb-src http://mirror.rackspace.com/ubuntu trusty main restricted

## Major bug fix updates produced after the final release of the
## distribution.
deb http://mirror.rackspace.com/ubuntu trusty-updates main restricted
deb-src http://mirror.rackspace.com/ubuntu trusty-updates main restricted

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
## team. Also, please note that software in universe WILL NOT receive any
## review or updates from the Ubuntu security team.
deb http://mirror.rackspace.com/ubuntu trusty universe
deb-src http://mirror.rackspace.com/ubuntu trusty universe
deb http://mirror.rackspace.com/ubuntu trusty-updates universe
deb-src http://mirror.rackspace.com/ubuntu trusty-updates universe

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu 
## team, and may not be under a free licence. Please satisfy yourself as to 
## your rights to use the software. Also, please note that software in 
## multiverse WILL NOT receive any review or updates from the Ubuntu
## security team.
deb http://mirror.rackspace.com/ubuntu trusty multiverse
deb-src http://mirror.rackspace.com/ubuntu trusty multiverse
deb http://mirror.rackspace.com/ubuntu trusty-updates multiverse
deb-src http://mirror.rackspace.com/ubuntu trusty-updates multiverse

## N.B. software from this repository may not have been tested as
## extensively as that contained in the main release, although it includes
## newer versions of some applications which may provide useful features.
## Also, please note that software in backports WILL NOT receive any review
## or updates from the Ubuntu security team.
deb http://mirror.rackspace.com/ubuntu trusty-backports main restricted universe multiverse
deb-src http://mirror.rackspace.com/ubuntu trusty-backports main restricted universe multiverse

deb http://mirror.rackspace.com/ubuntu trusty-security main restricted
deb-src http://mirror.rackspace.com/ubuntu trusty-security main restricted
deb http://mirror.rackspace.com/ubuntu trusty-security universe
deb-src http://mirror.rackspace.com/ubuntu trusty-security universe
deb http://mirror.rackspace.com/ubuntu trusty-security multiverse
deb-src http://mirror.rackspace.com/ubuntu trusty-security multiverse

## Uncomment the following two lines to add software from Canonical's
## 'partner' repository.
## This software is not part of Ubuntu, but is offered by Canonical and the
## respective vendors as a service to Ubuntu users.
# deb http://archive.canonical.com/ubuntu trusty partner
# deb-src http://archive.canonical.com/ubuntu trusty partner

## Uncomment the following two lines to add software from Ubuntu's
## 'extras' repository.
## This software is not part of Ubuntu, but is offered by third-party
## developers who want to ship their latest software.
# deb http://extras.ubuntu.com/ubuntu trusty main
# deb-src http://extras.ubuntu.com/ubuntu trusty main
```

@grossmj 
These same images works perfectly on local server.
Same image hashes on local and remote servers.

**Comment by noplay** [comment]
Could you try with repositiories? I suspect that rackspace as stripped the i386 packages from their mirror repositories. If it's the case I will see if I can copy the require package to our ppa. Since we also have the issue on another provider (packet).

```
###### Ubuntu Main Repos
deb http://us.archive.ubuntu.com/ubuntu/ trusty main restricted universe multiverse 

###### Ubuntu Update Repos
deb http://us.archive.ubuntu.com/ubuntu/ trusty-security main restricted universe multiverse 
deb http://us.archive.ubuntu.com/ubuntu/ trusty-updates main restricted universe multiverse 
deb http://us.archive.ubuntu.com/ubuntu/ trusty-backports main restricted universe multiverse

**Comment by AJNOURI** [comment]
Added the repositories and updated.
Still the same error:

> 2016-03-31 19:59:28 ERROR project.py:385 IOU process has stopped, return code: -11
> Error: IOU process has stopped, return code: -11

**Pull request merged**
